# Generated by Django 5.2 on 2025-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_remove_folder_title_af_remove_folder_title_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='folder',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='folder',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
